### ISSUE TITLE
Lab 9: Missing informations for configuring GitHub as OAuth provider

### ISSUE THREAD

**Issue by maximepires4** [adaltas/ece-webtech-2022-fall#10]
Hello,

In [lab 10 part 4.2](https://github.com/adaltas/ece-webtech-2022-fall/blob/main/courses/webtech/modules/09.oauth/lab.md#4-integration-of-oauth-with-supabase-hard-level) as well in [supabase doc](https://github.com/supabase/gotrue#external-authentication-providers), it is explained that we need to configure some values in `supabase/.env` file.

However, on my configuration this is not sufficient. I am not sure why but this error may appear on other configuration so here is my workaround.

I needed to edit the `supabase/docker-compose.yml` as well with the following configuration at the end of auth module environment variables:

```yaml
GOTRUE_EXTERNAL_GITHUB_ENABLED: ${GOTRUE_EXTERNAL_GITHUB_ENABLED}
GOTRUE_EXTERNAL_GITHUB_CLIENT_ID: ${GOTRUE_EXTERNAL_GITHUB_CLIENT_ID}
GOTRUE_EXTERNAL_GITHUB_SECRET: ${GOTRUE_EXTERNAL_GITHUB_SECRET}
GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI: ${GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI}
```

I guess there is some kind of linking needed, but as this error is not documented on the internet I don't know
